name: Build WASM Demo

on:
  push:
    branches: [ main ]
    paths:
      - "crates/geodb-wasm/**"
      - "crates/geodb-core/**"
      - "Cargo.toml"

jobs:
  wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Trunk + wasm-bindgen-cli
        run: |
          cargo install trunk
          cargo install wasm-bindgen-cli

      - name: Build WASM demo
        working-directory: crates/geodb-wasm
        run: trunk build --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: geodb-wasm-dist
          path: crates/geodb-wasm/dist
  attach-wasm-release-assets:
    needs: wasm
    # only when a GitHub Release is published
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest

    steps:
      - name: Download WASM dist artifact
        uses: actions/download-artifact@v4
        with:
          name: geodb-wasm-dist
          path: release-artifacts

      - name: Upload WASM dist to GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}   # e.g. v0.1.3
          files: release-artifacts/**        # index.html + wasm/js bundle